<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>School Passwords</title>
    <style>
        body { font-family: sans-serif; font-size: 12px; }
        table { width: 100%; border-collapse: collapse; }
        th { background: #287c44; color: white; padding: 8px; text-align: left; }
        td { padding: 6px; border: 1px solid #ddd; }
        .text-center { text-align: center; }
    </style>
</head>
<body>
    <h2 style="text-align: center; color: #287c44;">School Passwords List</h2>
    <p><strong>Total Records:</strong> {{ $total_records }}</p>
    <p><strong>Export Date:</strong> {{ $export_date }}</p>
    
    <table>
        <thead>
            <tr>
                <th>Sr.</th>
                <th>ID</th>
                <th>School ID</th>
                <th>School Name</th>
                <th>Password</th>
            </tr>
        </thead>
        <tbody>
            @foreach($passwords as $password)
            <tr>
                <td class="text-center">{{ $password['sr_no'] }}</td>
                <td class="text-center">{{ $password['id'] }}</td>
                <td class="text-center">{{ $password['school_id'] }}</td>
                <td>{{ $password['school_name'] }}</td>
                <td class="text-center">{{ $password['password_plain'] }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    
    <p style="text-align: center; margin-top: 20px; font-size: 10px;">
        Generated by {{ $exported_by }} on {{ $export_date }}
    </p>
</body>
</html>