<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Students Full Report</title>
    <style>
        /* Modern, standard PDF fonts */
        body {
            font-family: 'Helvetica', 'Arial', sans-serif;
            font-size: 12px;
            color: #333;
            line-height: 1.5;
            margin: 0;
            padding: 0;
        }

        /* Header Section */
        .header-container {
            border-bottom: 2px solid #287c44;
            padding-bottom: 10px;
            margin-bottom: 20px;
        }

        .header-title {
            font-size: 22px;
            font-weight: bold;
            color: #287c44;
            text-transform: uppercase;
            margin: 0;
        }

        .meta-info {
            width: 100%;
            margin-top: 10px;
        }

        .meta-info td {
            border: none;
            padding: 2px 0;
            font-size: 11px;
            color: #555;
        }

        /* Table Styling */
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        th {
            background-color: #287c44;
            color: #ffffff;
            font-weight: bold;
            text-transform: uppercase;
            font-size: 10px;
            padding: 10px 8px;
            border: 1px solid #287c44;
        }

        td {
            padding: 8px;
            border-bottom: 1px solid #eee;
            border-left: 1px solid #eee;
            border-right: 1px solid #eee;
        }

        /* Zebra Striping for readability */
        tbody tr:nth-child(even) {
            background-color: #f9f9f9;
        }

        /* Alignment and Utilities */
        .text-center { text-align: center; }
        .text-right { text-align: right; }
        .font-bold { font-weight: bold; }

        /* Badge/Status style for Grades */
        .grade-box {
            background: #eee;
            padding: 2px 6px;
            border-radius: 4px;
            font-weight: bold;
            display: inline-block;
        }

        /* Footer - Positioned at bottom */
        .footer {
            position: fixed;
            bottom: -30px;
            left: 0;
            right: 0;
            height: 50px;
            text-align: center;
            font-size: 10px;
            color: #999;
            border-top: 1px solid #eee;
            padding-top: 5px;
        }

        /* Page numbering (works in DomPDF) */
        .page-number:before {
            content: "Page " counter(page);
        }
    </style>
</head>

<body>
    <div class="header-container">
        <h1 class="header-title">Performance Report</h1>
        <table class="meta-info">
            <tr>
                <td width="33%"><strong>Year:</strong> {{ $year }}</td>
                <td width="33%"><strong>Category:</strong> {{ $category }}</td>
                <td width="33%" class="text-right"><strong>Level:</strong> {{ $levelName }}</td>
            </tr>
            <tr>
                <td><strong>Total Students:</strong> {{ count($allStudents) }}</td>
                <td></td>
                <td class="text-right"><strong>Report Date:</strong> {{ date('d M, Y') }}</td>
            </tr>
        </table>
    </div>

    <table>
        <thead>
            <tr>
                <th width="5%">#</th>
                <th width="20%">Student ID</th>
                <th>School Name</th>
                <th width="10%" class="text-center">Gender</th>
                <th width="10%" class="text-right">Total Marks</th>
                <th width="12%" class="text-right">Percentage</th>
                <th width="10%" class="text-center">Grade</th>
            </tr>
        </thead>
        <tbody>
            @foreach($allStudents as $index => $student)
                <tr>
                    <td class="text-center">{{ $index + 1 }}</td>
                    <td class="font-bold">{{ $student['student_id'] }}</td>
                    <td>{{ $student['school_name'] }}</td>
                    <td class="text-center">{{ ucfirst($student['gender']) }}</td>
                    <td class="text-right">{{ number_format($student['total_marks'], 2) }}</td>
                    <td class="text-right font-bold">{{ number_format($student['percentage'], 2) }}%</td>
                    <td class="text-center">
                        <span class="grade-box">{{ $student['grade'] }}</span>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Generated by Academic System | <span class="page-number"></span>
    </div>
</body>
</html>