<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Students Full Report</title>
    <style>
        body { 
            font-family: DejaVu Sans, sans-serif; 
            margin: 1cm;
        }
        .cover-page {
            text-align: center;
            margin-top: 5cm;
        }
        h1 { 
            color: #287c44; 
            font-size: 28px;
            margin-bottom: 20px;
        }
        .report-info {
            font-size: 14px;
            color: #666;
            margin: 10px 0;
        }
        .summary-box {
            margin-top: 2cm;
            padding: 20px;
            background-color: #f8fafc;
            border: 2px solid #287c44;
            border-radius: 10px;
            width: 60%;
            margin-left: auto;
            margin-right: auto;
        }
        .summary-item {
            font-size: 12px;
            margin: 10px 0;
            text-align: left;
        }
        .footer {
            position: absolute;
            bottom: 1cm;
            left: 1cm;
            right: 1cm;
            font-size: 10px;
            color: #999;
            text-align: center;
        }
    </style>
</head>
<body>
<div class="cover-page">
    <h1>Students Full Performance Report</h1>
    
    <div class="report-info">
        <p><strong>Year:</strong> {{ $year }}</p>
        <p><strong>Category:</strong> {{ $category }}</p>
        <p><strong>Level:</strong> {{ $levelName }}</p>
    </div>
    
    <div class="summary-box">
        <h3 style="color: #287c44;">Summary</h3>
        <div class="summary-item">
            <strong>Total Students:</strong> {{ $registeredStudents }}
        </div>
        <div class="summary-item">
            <strong>Report Generated:</strong> {{ now()->format('Y-m-d H:i:s') }}
        </div>
        <div class="summary-item">
            <strong>Generated By:</strong> {{ auth()->user()->name ?? 'System' }}
        </div>
    </div>
    
    <!-- Add Top Performers Summary -->
    <div class="top-performers-box" style="margin-top: 30px; padding: 15px; background-color: #f0f9ff; border: 2px solid #287c44; border-radius: 10px;">
        <h4 style="color: #287c44; margin-bottom: 15px;">🏆 Top 3 Performers</h4>
        @php
            $topThree = array_slice($all_student_ids, 0, 3);
            $topThreeData = [];
            foreach($topThree as $studentId) {
                $studentInfo = $studentId;
                $topThreeData[] = $studentInfo;
            }

            use App\Http\Controllers\Helper;
        @endphp
        
        <table style="width: 100%; border-collapse: collapse;">
            @foreach($topThreeData as $rank => $student)
      
            <tr>
                <td style="padding: 8px; border-bottom: 1px solid #ddd;">
                    <strong>#{{ $rank + 1 }}</strong>
                </td>
                <td style="padding: 8px; border-bottom: 1px solid #ddd;">
                     {{ Helper::parseStudentId((string) $student, 'student') ?? 'N/A' }}
                </td>
                <td style="padding: 8px; border-bottom: 1px solid #ddd;">
                    {{ Helper::parseStudentId((string) $student, 'school') ?? 'N/A' }}
                </td>
            </tr>
            @endforeach
        </table>
    </div>
</div>
    
    <div class="footer">
        This report contains {{ $registeredStudents }} students | Page 1
    </div>
</body>
</html>